config/routes.rb
Pig::Engine.routes.draw do
  # TODO: Allow this namespace to be defined in the Pig configuration

  root 'front/content_packages#home'


  scope "/#{Pig.configuration.mount_path}" do
    devise_for :users, class_name: 'Pig::User', module: :devise, controllers: {
      sessions: 'pig/admin/sessions',
      passwords: 'pig/admin/passwords',
      confirmations: 'pig/admin/confirmations'
    }
    devise_scope :user do
      patch 'users/confirmation' => 'admin/confirmations#update', :as => :update_user_confirmation
    end
  end

  scope "/#{Pig.configuration.mount_path}", as: "admin", module: "admin" do
    root 'content_types#dashboard', as: 'root'

    get 'not-authorized' => 'application#not_authorized'

    resources :content_types, except: :show do
      resources :content_packages, only: :new
      member do
        get 'children'
        get 'duplicate'
        get 'reorder'
        put 'reorder' => 'content_types#save_order'
      end
    end

    namespace :manage do
      resources :users do
        member do
          post :set_active
          post :deactivate
          post :confirm
          get :content
        end
      end
    end

    get '/content' => 'content_types#dashboard'
    post '/attachments' => 'attachments#create'

    resources :permalinks, only: [:destroy]

    resources :content_packages, except: :show do
      resources :comments, only: :create
      collection do
        get 'filter/:filter' => 'content_packages#index', :as => 'filter'
        get 'archived'
        get 'activity'
        get 'search'
      end
      member do
        get 'children'
        put 'archive'
        get 'reorder'
        put 'save_order'
        put 'restore'
        get 'activity'
        patch 'ready_to_review'
        get 'analytics'
      end
    end

    resources :navigation_items do
      collection do
        get 'reorder'
        put 'reorder' => 'navigation_items#save_order'
        get :search
      end
      member do
        get 'reorder'
        put 'reorder' => 'navigation_items#save_order'
      end
    end

    get '/persona/report' => 'personas#report'
    get '/persona/pages/:id/:status' => 'personas#report_pages'

    resources :personas
    resources :meta_data
    resources :redactor_image_uploads, only: [:index, :create]

    if Pig.configuration.tags_feature
      resources :tag_categories, path: :tags, except: [:show, :destroy]
    end
  end

  get '404' => 'front/errors#not_found',
      via: [:get, :post, :patch, :delete],
      as: 'not_found'

  get '//*id/edit', to: 'admin/content_packages#edit'
  get '//*path/preview', to: 'front/content_packages#preview', as: 'preview_admin_content_package'
  get '//*path', to: 'front/content_packages#show', as: 'content_package'
end

app/models/pig/ability.rb
module Pig
  class Ability
    include CanCan::Ability

    DEVELOPER_ABILITIES = {
      'Pig::ContentType' => [
        :manage_description,
        :manage_package_name,
        :manage_view_name,
        :manage_viewless,
        :manage_singleton
      ],
      'Pig::ContentPackage' => [
        :manage_slug
      ],
      'Pig::Permalink' => [
        :destroy
      ]
    }

    def initialize(user)
      can :home, Pig::ContentPackage
      can :show, Pig::ContentPackage do |content_package|
        content_package.visible_to_user?(nil)
      end

      return unless user

      can [:create, :index], RedactorImageUpload
      can [:edit, :show, :update], Pig::User, id: user.id
      if user.role_is?(:developer)
        can :manage, :all
      elsif user.role_is?(:admin)
        can :manage, :all
        cannot :alter_role, Pig::User
        can :alter_role, Pig::User do |other_user|
          other_user.role.to_sym.in?(user.available_roles)
        end
        DEVELOPER_ABILITIES.each do |klass, actions|
          actions.each do |action|
            cannot action, klass.constantize
          end
        end
        can :destroy, Pig::Permalink do |permalink|
          instance_exec permalink, &Pig.configuration.can_delete_permalink
        end
      elsif user.role_is?(:editor)
        can [:edit, :update], Pig::ContentPackage, :author_id => user.id
        can [:manage], Pig::ContentPackage
        cannot :destroy,  Pig::ContentPackage
        can [:index, :dashboard, :children], Pig::ContentType
        can [:create], Pig::Comment
        can [:create, :show], Pig::Permalink
        can :destroy, Pig::Permalink do |permalink|
          instance_exec permalink, &Pig.configuration.can_delete_permalink
        end
        can [:index, :edit], Pig::Persona
      elsif user.role_is?(:author)
        cannot :manage, Pig::Permalink
        can [:edit, :update], Pig::ContentPackage, :author_id => user.id
        can [:index, :show, :activity, :ready_to_review, :search, :preview], Pig::ContentPackage
        can [:index, :dashboard, :children], Pig::ContentType
        can :contributor_blog_posts, Pig::ContentPackage
        can [:create], Pig::Comment
        can [:children], Pig::ContentPackage
        can [:index, :edit], Pig::Persona
      end
    end
  end
end

app/models/pig/activity_item.rb
module Pig
  class ActivityItem < ActiveRecord::Base

    belongs_to :user
    belongs_to :resource, :polymorphic => true, optional: true
    belongs_to :parent_resource, :polymorphic => true, optional: true
    validates :user, :presence => true

    def next
      return self if user.nil?
      next_activity = user.activity_items.where(resource_id: resource_id).where("id > ?", id).last
      if next_activity
        next_activity
      else
        self
      end
    end


    def previous
      return self if user.nil?
      previous_activity = user.activity_items.where(resource_id: resource_id).where("id < ?", id).first
      if previous_activity
        previous_activity
      else
        self
      end
    end

    class << self

      def default_scope
        order("created_at DESC")
      end

    end

  end
end

app/models/pig/analytics.rb
module Pig
  class Analytics

    attr_reader :referrers

    def initialize(results)
      @referrers = results.group_by(&:source).map { |x| Referrer.new(x) }
      @totals = results.totals_for_all_results
    end

    def as_json(options={})
      {
        total: @totals['pageviews'],
        referrers: @referrers,
        avg_time_on_page: @totals['avgTimeOnPage'].to_i
      }
    end

  end

  class Referrer
    def initialize(referrer)
      @name = referrer[0]
      @keywords = referrer[1].map { |x| Keyword.new(x) }
    end

    def total
      @keywords.collect(&:total).sum
    end

    def as_json(options={})
      {
        name: @name,
        total: total,
        keywords: @keywords
      }
    end

  end

  class Keyword

    attr_reader :word, :total

    def initialize(keyword)
      @word = keyword.keyword
      @total = keyword.pageviews.to_i
    end

    def as_json(options={})
      {
        total: @total,
        word: @word
      }
    end
  end

end

app/models/pig/comment.rb
module Pig
  class Comment < ActiveRecord::Base
    include ActsAsCommentable::Comment
    include ActionView::Helpers::DateHelper

    belongs_to :commentable, :polymorphic => true
    belongs_to :user

    default_scope -> { order('created_at ASC') }

    def serializable_hash(options={})
      options ||= {}
      options = {
        methods: [:pretty_time, :formatted_created_at],
        include: :user
      }.update(options)
      super(options)
    end

    def pretty_time
      time_ago_in_words(created_at)
    end

    def formatted_created_at
      created_at.strftime("%e %B %Y, %I:%M")
    end

  end
end

app/models/pig/concerns/commentable.rb
module Pig
  module Concerns
    module Commentable
      extend ActiveSupport::Concern

      included do
        acts_as_commentable
      end

    end
  end
end

app/models/pig/concerns/recordable.rb
require 'active_support/concern'

module Pig
  module Concerns
    module Recordable
      extend ActiveSupport::Concern

      included do
        has_many :activity_items, :as => :resource, :class_name => "ActivityItem"
        attr_accessor :editing_user
        validates :editing_user, presence: true
        after_create { record_activity!(self.editing_user, "#{self.name} was created") }
        after_update :record_update_activity
        before_destroy { record_activity!(self.editing_user, "#{self.name} was permanently deleted") }
      end

      def record_update_activity
        if self.archived_at_changed?
          if archived_at_was.nil?
            record_activity!(self.editing_user,  "#{self.name} was #{I18n.t('actions.archived').downcase}")
          else
            record_activity!(self.editing_user,  "#{self.name} was restored")
          end
        else
          record_activity!(self.editing_user,  "#{self.name} was updated")
        end
      end

      def record_activity!(user, text)
        return unless user
        if Pig::ActivityItem.where(resource_id: self.id, created_at: 1.seconds.ago..Time.now).empty? # Avoid creating duplicate activity items
          self.activity_items.create(user_id: user.id, text: text)
        end
      end
    end
  end
end

app/models/pig/concerns/versionable.rb
# When using versionable the live version published on the site
# is always the last paper_trail version. The preview version
# is the canonical non-versioned instance of the model.

module Pig
  module Concerns
    module Versionable
      extend ActiveSupport::Concern

      included do
        has_paper_trail class_name: 'Pig::Version',
                        if: proc { |t| t.status_was == 'published' }
      end

      def live_version
        return self if published?
        return versions.last.reify if versions.any?
        self
      end

      def preview_version
        # get the non-versioned model
        @preview_version ||= self.class.find(id)
      end

    end
  end
end

app/models/pig/concerns/workflow.rb
require 'active_support/concern'

module Pig
  module Concerns
    module Workflow
      extend ActiveSupport::Concern

      included do
        before_save :execute_transitions
      end

      class_methods do
        def statuses(user)
          statuses_for(user, self)
        end

        def check_ability(ability, instance, user)
          (ability || user).can? :manage, instance
        end

        def statuses_for(user, instance, ability = nil)
          statuses = {}
          statuses[:draft] = 'Draft' if check_ability(ability, instance, user)
          statuses[:pending] = 'Ready to review'
          if (instance.try(:status) == 'published' ||
              instance.try(:status) == 'update' ||
              instance.try(:status) == 'pending') &&
             check_ability(ability, instance, user)
            statuses[:update] = 'Needs updating'
          end
          statuses[:published] = 'Published' if check_ability(ability, instance, user)
          statuses[:expiring] = 'Getting old' if check_ability(ability, instance, user)
          statuses
        end

      end

      def statuses(user, ability)
        self.class.statuses_for(user, self, ability)
      end

      def execute_transitions
        execute_status_transition if status_changed?
        execute_author_transition if author_id_changed?
      end

      def execute_status_transition
        transitions = {
          draft: {
            pending: :ready_to_review,
            published: :notify_author_of_publish
          },
          pending: {
            draft: :assign_to_author,
            published: :notify_author_of_publish
          },
          published: {
            draft: :assign_to_author,
            published: :notify_author_of_publish,
            update: :notify_author_of_amends
          },
          update: {
            published: :notify_author_of_publish,
            pending: :ready_to_review
          },
          expiring: {}
        }
        event = transitions[status_was.to_sym][status.to_sym]
        send(event) if event
      end

      def execute_author_transition
        return if author.nil?
        assign_to_author
      end

      def notify_author_of_publish
        return if editing_user == last_edited_by
        return if last_edited_by.nil?
        ContentPackageMailer.published(self, last_edited_by).deliver_now
      end

      def ready_to_review
        self.last_edited_by_id = author_id
        self.author_id = nil
        return if requested_by.nil?
        ContentPackageMailer.assigned_for_review(self, requested_by).deliver_now
      end

      def assign_to_author
        return if @author_already_notified
        return if author.nil?
        ContentPackageMailer.assigned_for_writing(self, author).deliver_now
        @author_already_notified = true
      end

      def notify_author_of_amends
        return if @author_already_notified
        return if author.nil?
        ContentPackageMailer.assigned_for_updating(self, author).deliver_now
        @author_already_notified = true
      end
    end
  end
end

app/models/pig/content_attribute.rb
module Pig
  class ContentAttribute < ActiveRecord::Base

    belongs_to :content_type
    belongs_to :default_attribute, :class_name => 'ContentAttribute', optional: true
    after_validation :set_meta_title, :if => :meta?
    before_validation :set_slug
    validates :slug, :name, :field_type, :presence => true
    begin
      validates :slug, :name,
        uniqueness: { scope: :content_type_id },
        exclusion: {
          in: Pig::ContentPackage.methods + Pig::ContentPackage.column_names,
          message: "%{value} is a reserved word."
        }
    rescue ActiveRecord::StatementInvalid
      # Migrations not yet carried out, but need to be able to precompile
    end
    belongs_to :resource_content_type, :class_name => 'ContentType', optional: true


    class << self

      def field_types
        {
          string: 'Single line of text',
          text: 'Block of text',
          link: 'Link',
          image: 'Image',
          file: 'File',
          embeddable: 'Embeddable content - Flickr, Instagram, Scribd, Slideshare, SoundCloud, Vimeo, YouTube',
          tags: 'Tag list',
          boolean: 'Check box',
          user: 'User',
          location: 'Location',
          resource: 'Link to content',
          rich_content: 'Rich Content',
          date: 'Date',
          time: 'Time'
        }.merge(Pig.configuration.content_types)
      end

      def fields_to_duplicate
        column_names - %w{id content_type_id slug position}
      end

    end

    META_TAG_TYPES = ["title", "description", "image", "keywords"]

    def field_type
      ActiveSupport::StringInquirer.new(read_attribute(:field_type).to_s)
    end

    def input_type
      case field_type
      when 'file' then 'file_with_preview'
      when 'text' then 'redactor'
      when 'boolean' then 'content_boolean'
      when 'user' then 'select'
      when 'resource' then 'autocomplete_select'
      when 'rich' then 'text'
      when 'rich_content' then 'rich_redactor'
      when 'date' then 'date_picker'
      when 'time' then 'ym_time_picker'
      else field_type
      end
    end

    def input_method
      case field_type
      when 'embeddable' then slug + "_url"
      when 'tags' then slug.singularize + "_list"
      when 'user' then slug + "_id"
      else slug
      end
    end

    def input_options
      case field_type
      when 'user'
        {
          :collection => Pig::User.all,
          :prompt => "None selected"
        }
      when 'resource'
        {
          :collection => resource_collection,
          :prompt => "None selected",
        }
      else {}
      end
    end

    def resource_collection
      # ContentPackage collection for atrributes of type resource
      resource_content_type.nil? ? Pig::ContentPackage.published : Pig::ContentPackage.where(content_type: resource_content_type).published
    end

    def limitable?
      %w{string text}.include?(field_type.to_s)
    end

    def removable?
      new_record? || content_type.missing_view?
    end

    def to_s
      name
    end

    private

    def set_meta_title
      unless name.start_with?('Meta ')
        self.name = 'Meta ' << name
        valid?
      end
    end

    def set_slug
      return unless slug.blank? && name.present? && errors['name'].blank?
      if Rails.version.to_f >= 5.0
        slug_name = name.gsub('-', ' ').parameterize(separator: '_').sub(/^\d+/, 'n')
      else
        slug_name = name.gsub('-', ' ').parameterize('_').sub(/^\d+/, 'n')
      end
      if Pig::ContentPackage.new.respond_to?(slug_name)
        slug_name = 'content_package_' + slug_name
      end
      self.slug = slug_name
      valid?
    end

  end
end

app/models/pig/meta_datum.rb
module Pig
  class MetaDatum < ActiveRecord::Base

    dragonfly_accessor :image
    validates :page_slug, presence: true

    def to_s
      "/#{page_slug}"
    end
  end
end

app/models/pig/persona_group.rb
module Pig
  class PersonaGroup < ActiveRecord::Base
    
    has_many :personas, :foreign_key => :group_id
    validates :name, :presence => true

    def to_s
      name
    end

  end
end

app/models/pig/redactor_image_upload.rb
module Pig
  class RedactorImageUpload < ActiveRecord::Base

    dragonfly_accessor :file
    validates_property :format, of: :file, in: ['jpeg', 'png', 'gif']
    validates :file, presence: true

    def image
      file_type == 'image' ? file : nil
    end
  end
end

app/models/pig/resource_tag_category.rb
module Pig
  class ResourceTagCategory < ActiveRecord::Base

    belongs_to :tag_category
    belongs_to :taggable_resource, :polymorphic => true
  end
end

app/views/pig/users/_form.html.haml
=semantic_form_for(@user, cms_user_url_and_method_create_edit(@user)) do |form|
  =form.inputs do
    .half-input
      =form.input :first_name
    .half-input
      =form.input :last_name
    .clearfix
    =form.input :email
    -if current_user.is_admin?
      =form.input :role, :as => :select, :collection => Pig::User.available_roles, :include_blank => false
    -if @user.new_record?
      =form.input :password
    -else
      =form.input :bio, :input_html => {:rows => 5, :class => 'span4'}
      =form.input :image, :as => :image
      =form.input :active
  =hidden_field_tag :return_to, params[:return_to] if params[:return_to]
  =form.actions do
    =form.action :submit, :label => 'Save', :button_html => {:class => 'btn btn-success pull-right'}
    .btn=link_to('View all users', '/cms/cms_users')

app/views/pig/users/index.html.haml
:javascript
  $(document).ready(function() {
    window.userFilter().init();
  });
.container
  .row
    .col-xs-12
      .cms-page-header
        .row
          .col-sm-6.col-sm-offset-3
            %h1=title("Users")
          .col-sm-3.cms-header-actions
            -if can? :new, Pig::User
              =link_to("Add new user", new_pig_user_path, :icon => 'plus', :class => 'btn btn-success')
.container.page-margin-bottom
  .col-md-12
    
    %table.cms-table.users-table
      %thead
        %tr
          %th Name
          %th Role
          %th.filter-control
            .sitemap-filter.pull-right
              %strong Filter
              &nbsp;
              =select_tag(:role, options_for_select([['All', nil]] + Pig::User.available_roles, params[:filter]), :class => 'noselectpicker')
            %label.pull-right.m0
              =check_box_tag :show_inactive, '', @show_inactive
              Include inactive users
      %tbody
        -@users.each do |user|
          %tr.user-row{'data_user-id' => user.id, :class => "role-#{user.role} " + (user.active ? 'active' : 'inactive')}
            %td.user-name
              =link_to(user.full_name, pig_user_path(user))
            %td.user-role
              =user.role

            %td.user-actions
              -action = user.active ? 'deactivate' : 'reactivate'
              -btn_class = user.active ? 'btn-default' : 'btn-warning'
              =link_to('Edit', edit_pig_user_path(user), class: 'btn btn-xs btn-success edit-user-btn')
              =link_to( user.active ? 'Deactivate' : 'Reactivate', pig_set_active_user_path(user), remote: true, method: :post, class: "btn btn-xs set-active-btn #{btn_class}" , :data => {:confirm => "Are you sure you want to #{action} this user?"})
              =link_to('Delete', pig_user_path(user), method: :delete, data: {confirm: 'Are you sure? This user will be permanently removed and cannot be restored.'}, remote: true,class: 'btn btn-xs btn-error delete-user-btn')

app/views/pig/users/show.html.haml
.container.cms-main
  .cms-page-header.cms-page-header-left
    .row.section-margin
      .col-sm-2
        .image-wrapper
          =image_for(@user, "200x200#")
      .col-sm-7
        %h3.mt-0=title(@user)
        .col-sm-2.p0
          .label.upper Status
          =@user.active ? 'Active' : 'Inactive'
        .col-sm-6.col-xs-12.p0
          .label.upper Email
          =link_to(@user.email, 'mailto:'+ @user.email)
        .col-sm-2.p0
          .label.upper Role
          -if @user.role.present?
            =@user.role
          -else
            =link_if_can("Set a role for this user", [:edit, @user])
        .clearfix.section-margin
        .label.upper Biography
        -if @user.bio.present?
          =@user.bio
        -else
          =link_if_can("Write a bio for this user", [:edit, @user])
      .col-md-3
        =link_if_can("Edit user", [:edit, @user] ,:class => 'btn btn-success  pull-right')
        .btn.pull-right=link_to('See all users', '/cms/cms_users')
    -if @assigned_content.present? 
      .row.section-margin
        .col-xs-12
          .allocated_content
            %table.cms-table
              %thead
                %tr
                  %th.text-left{colspan: 4}
                    Content assigned to
                    =title(@user.first_name)
              %tbody
                -@assigned_content.each do |content_package|
                  %tr
                    %td.table-page
                      =content_package.name
                    %td.table-action
                      =link_to('View', content_package, :class => 'btn btn-xs btn-default') unless content_package.viewless? || content_package.missing_view?
                      -if can? :edit, content_package
                        =link_to('Edit', edit_pig_content_package_path(content_package), :class => 'btn btn-xs btn-success')