config/routes.rb
Pig::Engine.routes.draw do
  # TODO: Allow this namespace to be defined in the Pig configuration

  root 'front/content_packages#home'


  scope "/#{Pig.configuration.mount_path}" do
    devise_for :users, class_name: 'Pig::User', module: :devise, controllers: {
      sessions: 'pig/admin/sessions',
      passwords: 'pig/admin/passwords',
      confirmations: 'pig/admin/confirmations'
    }
    devise_scope :user do
      patch 'users/confirmation' => 'admin/confirmations#update', :as => :update_user_confirmation
    end
  end

  scope "/#{Pig.configuration.mount_path}", as: "admin", module: "admin" do
    root 'content_types#dashboard', as: 'root'

    get 'not-authorized' => 'application#not_authorized'

    resources :content_types, except: :show do
      resources :content_packages, only: :new
      member do
        get 'children'
        get 'duplicate'
        get 'reorder'
        put 'reorder' => 'content_types#save_order'
      end
    end

    namespace :manage do
      resources :users do
        member do
          post :set_active
          post :deactivate
          post :confirm
          get :content
        end
      end
    end

    get '/content' => 'content_types#dashboard'
    post '/attachments' => 'attachments#create'

    resources :permalinks, only: [:destroy]

    resources :content_packages, except: :show do
      resources :comments, only: :create
      collection do
        get 'filter/:filter' => 'content_packages#index', :as => 'filter'
        get 'archived'
        get 'activity'
        get 'search'
      end
      member do
        get 'children'
        put 'archive'
        get 'reorder'
        put 'save_order'
        put 'restore'
        get 'activity'
        patch 'ready_to_review'
        get 'analytics'
      end
    end

    resources :navigation_items do
      collection do
        get 'reorder'
        put 'reorder' => 'navigation_items#save_order'
        get :search
      end
      member do
        get 'reorder'
        put 'reorder' => 'navigation_items#save_order'
      end
    end

    get '/persona/report' => 'personas#report'
    get '/persona/pages/:id/:status' => 'personas#report_pages'

    resources :personas
    resources :meta_data
    resources :redactor_image_uploads, only: [:index, :create]

    if Pig.configuration.tags_feature
      resources :tag_categories, path: :tags, except: [:show, :destroy]
    end
  end

  get '404' => 'front/errors#not_found',
      via: [:get, :post, :patch, :delete],
      as: 'not_found'

  get '//*id/edit', to: 'admin/content_packages#edit'
  get '//*path/preview', to: 'front/content_packages#preview', as: 'preview_admin_content_package'
  get '//*path', to: 'front/content_packages#show', as: 'content_package'
end

app/models/pig/navigation_item.rb
module Pig
  class NavigationItem < ActiveRecord::Base

    belongs_to :parent, :class_name => 'NavigationItem'
    belongs_to :resource, :polymorphic => true
    has_one :grandparent, :through => :parent, :source => :parent
    has_many :children, -> { order(:position) }, :class_name => 'NavigationItem', :foreign_key => :parent_id

    attr_writer :link
    dragonfly_accessor :image
    dragonfly_accessor :logo

    validates :title, :presence => true

    before_validation :process_link

    scope :root, lambda{ where(:parent_id => nil).order(:position) }
    scope :level_two, lambda{ joins(:parent).where(:parents_navigation_items => {:parent_id => nil})}
    scope :level_three, lambda{ joins(:grandparent).where(:grandparents_navigation_items => {:parent_id => nil})}

    def depth
      parents.size
    end

    def linkable
      url.presence || resource
    end

    def name
      title
    end

    def parents
      [parent, parent.try(:parents)].flatten.compact
    end

    private
    def process_link
      if @link == ''
        self.url = nil
        self.resource = nil
      elsif !@link.nil?
        path = @link.to_s.sub(/^\//,'')
        if permalink = Permalink.find_by_path(path.downcase)
          self.resource = permalink.resource
          self.url = nil
        else
          self.url = @link
          self.resource = nil
        end
      end
    end

  end
end

app/controllers/pig/admin/navigation_items_controller.rb
module Pig
  module Admin
    class NavigationItemsController < Pig::Admin::ApplicationController
      load_and_authorize_resource class: 'Pig::NavigationItem'

      def create
        @navigation_item.save
        render :action => 'create_update'
      end

      def destroy
        @navigation_item.destroy
      end

      def edit
        render :action => 'new_edit'
      end

      def index
      end

      def new
        @navigation_item.parent_id = params[:parent_id]
        render :action => 'new_edit'
      end

      def reorder
        @navigation_items = @navigation_item.try(:children) || Pig::NavigationItem.root
      end

      def save_order
        params[:children_ids].each_with_index do |child_id, position|
          Pig::NavigationItem.find(child_id).update_attribute(:position, position)
        end
        redirect_to pig.admin_navigation_items_path
      end

      def search
        if defined?(Riddle)
          term = Riddle.escape(params[:term])
        else
          term = params[:term]
        end
        render :json => Pig::ContentPackage.search(term).includes(:permalink).map { |cp| {
            :id => cp.id,
            :label => cp.name.truncate(60),
            :value => cp.permalink_display_path
        }}
      end

      def update
        @navigation_item.update_attributes(params[:navigation_item])
        render :action => 'create_update'
      end

    end
  end
end

app/views/pig/admin/navigation_items/_form.html.haml
-content_for :javascript do
  :javascript
    NavigationManager.init()
.modal-header
  %button.close{'data-dismiss' => "modal"} &times;
  %h4.modal-title Navigation item
=semantic_form_for @navigation_item, :remote => true do |form|
  .modal-body
    =form.inputs do
      =form.input :parent_id, :as => :hidden
      =form.input :title
      -if @navigation_item.depth.zero?
        =form.input :item_type, :label => "Type", :as => :select, :collection => [["Link", 'link'], ['Dropdown', 'dropdown']], :include_blank => false
      =form.input :link, :label => "Link - <em>type the name of an existing page on the site, or enter a URL e.g. '/volunteer'</em>".html_safe, :input_html => {:value => (@navigation_item.url || (@navigation_item.resource ? polymorphic_path(@navigation_item.resource) : nil))}, :wrapper_html => {:style => "display:#{@navigation_item.item_type == 'dropdown' ? 'none' : 'block'};"}
      -if @navigation_item.depth == 1
        =form.input :description, :input_html => {:rows => 2}
        =form.input :image, :as => :image, :label => "Large image - <em>used when on the top row of the dropdown</em>".html_safe, :remove_label => "Remove large image"
        =form.input :logo, :as => :image, :label => "Logo image - <em>used when on or below the second row of the dropdown</em>".html_safe, :remove_label => "Remove logo image"
  .modal-footer
    =form.actions do
      =form.action :submit, :label => 'Submit', :button_html => {:class => 'btn btn-primary btn-block'}

app/views/pig/admin/navigation_items/_navigation_item.html.haml
- parents = parents.try(:dup) || []
%tr.navigation-item{:class => "#{'has-children' unless navigation_item.children.count.zero?}"}
  %td.td-name
    =sitemap_spacers(navigation_item, parents)
    %span.name
      -unless navigation_item.children.count.zero?
        %i.fa.sitemap-caret.fa-caret-down
      =navigation_item.title
  %td.td-link
    -if navigation_item.item_type != 'dropdown' && navigation_item.linkable
      =link_to((navigation_item.url || (navigation_item.resource ? polymorphic_path(navigation_item.resource) : nil)), navigation_item.linkable, :target => '_blank')
  %td.td-actions
    =link_to('Edit', edit_navigation_item_path(navigation_item), :remote => true)
    &nbsp;
    =link_to('Delete', navigation_item_path(navigation_item), :remote => true, :method => :delete, :data => {:confirm => "Are you sure you want to delete this?"})
    -if parents.size < 2
      &nbsp;
      =link_to('Add child', new_navigation_item_path(:parent_id => navigation_item.id), :remote => true)
      -if navigation_item.children.size > 1
        &nbsp;
        =link_to('Reorder children', reorder_navigation_item_path(navigation_item))
- parents << navigation_item
-navigation_item.children.each do |child|
  =render('navigation_items/navigation_item', :navigation_item => child, :parents => parents)

app/views/pig/admin/navigation_items/_table.html.haml
%table.table
  %thead
    %tr
      %th Title
      %th Link
      %th.text-right Actions
  %tbody
    -navigation_items.root.each do |navigation_item|
      =render 'navigation_items/navigation_item', :navigation_item => navigation_item
    %tr.text-right
      %td.pt-4{:colspan => 6}
        =link_to("Reorder top level items", reorder_navigation_items_path, :class => 'btn btn-primary')
        =link_to("Add top level item", new_navigation_item_path, :remote => true, :class => 'btn btn-confirm')

app/views/pig/admin/navigation_items/create_update.js.erb
<% if @navigation_item.valid? %>
$('#nav-modal').modal('hide');
$('#nav-modal .modal-content').html('');
$('#nav-table').html('<%=escape_javascript(render('table', :navigation_items => NavigationItem.root))%>');
$('#main-header').html('<%=escape_javascript(render('layouts/header'))%>');
<% else %>
$('#nav-modal .modal-content').html('<%=escape_javascript(render('form'))%>');
<% end %>

app/views/pig/admin/navigation_items/destroy.js.erb
$('#nav-table').html('<%=escape_javascript(render('table', :navigation_items => NavigationItem.root))%>');
$('#main-header').html('<%=escape_javascript(render('layouts/header'))%>');

app/views/pig/admin/navigation_items/index.html.haml
=render('sitemap_header', header_title: 'Navigation manager')
.container
  .tab-content.tab-content-sitemap
    #navigation-manager.tab-pane.active
      #nav-table.sitemap
        =render('navigation_items/table', :navigation_items => NavigationItem.root)
      #nav-modal.modal.fade
        .modal-dialog
          .modal-content

app/views/pig/admin/navigation_items/new_edit.js.erb
$('#nav-modal').modal('hide');
$('#nav-modal .modal-content').html('<%=escape_javascript(render('form'))%>');
$('#nav-modal').modal();

app/views/pig/admin/navigation_items/reorder.html.haml
-content_for :javascript do
  :javascript
    $(document).ready(function(){Pig.Sortable.init();});

%h3 Reorder children
%p
  Drag and drop the children into the desired order and click
  %em Save order.
%form.formtastic.form-horizontal.form-sortable
  %fieldset.inputs
    .controls.sortable
      -@navigation_items.each do |child|
        .well{:id => "children_ids_#{child.id}"}
          =child
  %fieldset.form-actions
    =link_to('Save order', @navigation_item ? reorder_navigation_item_path(@navigation_item) : reorder_navigation_items_path, :method => :put, :class => 'btn sortable-submit mb-3')